# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yangruimm.github.io
title: My - 杨心心心
email: yanrui950808@163.com
author: 杨蕊
description: > # "Write an awesome description for your new site here. 
  UI设计师，UED，交互设计。天津商业大学学生
copyright: 'Copyright &copy; 2016 My - 杨心心心. All Rights Reserved.'


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: http://yangruimm.github.io
  - title: github
    url: http://yangruimm.github.io
  - title: linkedin
    url: http://yangruimm.github.io
